FROM rustlang/rust:nightly

ARG DATABASE_URL

WORKDIR /usr/src/archetype

COPY . .

RUN cargo install --path .
RUN cargo install diesel_cli
#RUN cargo build --release

CMD ["docker/start-web-service.sh"]
