openapi: 3.0.3
info:
  title: Archetype
  description: A User Avatar service, designed for FoamFactory, usable for anything
  version: 1.0.6
  contact:
    name: "Scott Johnson"
    url: "https://github.com/FoamFactory/archetype"
    email: "scott@foamfactory.io"
tags:
  - name: Avatars
    description: |
      Methods used to affect records of Avatars in the database.
components:
  responses:
    Avatar:
      description: |
        Response containing a single `UserAvatar` object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserAvatar'
    BadRequest:
      description: |
        The parameters given for the particular request were not correct.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/DetailedErrorMessage'
              - properties:
                  error:
                    example: 'File Corrupted'
    DehydratedUserAvatarList:
      description: 'Response containing an array of `DehydratedUserAvatar` objects'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DehydratedAvatarList'
    NotFoundError:
      description: |
        The record with the requested `id` was not found in the system.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/DetailedErrorMessage'
              - properties:
                  error:
                    example: 'A record of type Avatar having id 111 was not found'
    PayloadTooLarge:
      description: |
        An error that is thrown when avatar images exceed the size allocated (2MB by default).
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/Message'
              - properties:
                  message:
                    example:
                      'File must be less than 2MB in size'
    Success:
      description: |
        A message indicating that the operation succeeded.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/Message'
              - properties:
                  message:
                    example:
                      'Successfully deleted Avatar with id 3'
    UnsupportedMediaType:
      description: |
        Returned if an image is sent with a mime type other than `image/jpeg` or `image/png`.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/DetailedErrorMessage'
              - properties:
                  error:
                    example: 'Image data sent is not in PNG or JPG format'
  schemas:
    AvatarUri:
      description: 'An object containing a data URI that contains the binary data of an image to be used as an avatar.'
      type: object
      properties:
        data_uri:
          description: 'The data URI containing the image data to use as an avatar.'
          type: string
          example: 'data:image/png;base64,...'
    DehydratedUserAvatar:
      description: |
        An object containing the data relevant for a user's avatar, minus the actual avatar itself.
      type: object
      properties:
        id:
          type: number
          description: 'The database ID of the record. Guaranteed to be unique over all `UserAvatar` objects.'
          example: 1234
        mimetype:
          type: string
          example: "image/jpeg"
          description: |
            The MIME type of the image data. Must be one of 'image/jpeg' or 'image/png'.
    DetailedErrorMessage:
      description: 'An object containing a more specific internal error code and a detailed message to the client about what occurred on the server.'
      type: object
      properties:
        error:
          description: 'A human-readable message to the client indicating what specifically happened.'
          type: string
          example: 'Some example message'
    Message:
      description: 'An object containing a simple message'
      type: object
      properties:
        message:
          description: 'A human-readable message'
          type: string
          example: "Successfully deleted 1 record"
    UserAvatar:
      description: |
        An object containing the data relevant for a user's avatar.
      type: object
      properties:
        id:
          type: number
          description: 'The database ID of the record. Guaranteed to be unique over all `UserAvatar` objects.'
          example: 1234
        mimetype:
          type: string
          description: |
            The MIME type of the image data. Must be one of 'image/jpeg' or 'image/png'.
        image:
          type: string
          description: 'A base64 encoded representation of the image that will serve as the avatar.'
          example: |
            iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAIAAAACUFjqAAABj2lDQ1BJQ0MgcHJvZmlsZQAAKJF9kb1Lw1AUxU9TxSotIjqIdMhQHcSCKIiDi1UsQoVSK1h1MHnph5CkIUlxcRRcCw6ii1+D/gGiq4OrIAiKIOLkH+DXIiXelwRapPXB4/5ycu/hvfMA4VxlmtU2Cmi6bWaSCXE5tyJ2vEFABD0Io1NiljGdTqfQcn0/IMDrfZx7te5ruiJK3mJAQCSeY4ZpE5eIJzZtg/MRcR8rSQrxBfGISQckfuW67PEn56LLQoizmc3MEEeJxWIDyw3MSqZGPEUcUzSd/IV1jxXO25w1tcL8c/IbhvP60iLVYdpRJKFiAxoMWMhDhIwKfauwEaeqk2IhQ10Jyra5z4Drk6Y52fViNDOLMnlKrgP4W/zN2CqMj3lOYXJuf3Gcj0GgYxeoVR3n59hxaidA8Bm41uvzZcpx8ov0al2LHQLddM/Lm7om7wFXO0D/kyGZkisFaQuFAvB+Rs+VA3rvgK5VLz//P04fgewWkLoF9g+AoSJ5r7W4d8jPbx4LSP/b4yf4C4vSdIzDS13OAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAB3RJTUUH5gINEQwu6eRSBgAAABx0RVh0Q29tbWVudABDcmVhdGVkIHdpdGggR2xpbXBzZe5OGAcAAAAUSURBVBjTY/x/jgEPYGJgGJXGBAA5EwHhXz/1YwAAAABJRU5ErkJggg==
        data_uri:
          type: string
          description: 'A convenience interpretation of a data URI for browsers so that the image can be directly displayed.'
          example: |
            data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAIAAAACUFjqAAABj2lDQ1BJQ0MgcHJvZmlsZQAAKJF9kb1Lw1AUxU9TxSotIjqIdMhQHcSCKIiDi1UsQoVSK1h1MHnph5CkIUlxcRRcCw6ii1+D/gGiq4OrIAiKIOLkH+DXIiXelwRapPXB4/5ycu/hvfMA4VxlmtU2Cmi6bWaSCXE5tyJ2vEFABD0Io1NiljGdTqfQcn0/IMDrfZx7te5ruiJK3mJAQCSeY4ZpE5eIJzZtg/MRcR8rSQrxBfGISQckfuW67PEn56LLQoizmc3MEEeJxWIDyw3MSqZGPEUcUzSd/IV1jxXO25w1tcL8c/IbhvP60iLVYdpRJKFiAxoMWMhDhIwKfauwEaeqk2IhQ10Jyra5z4Drk6Y52fViNDOLMnlKrgP4W/zN2CqMj3lOYXJuf3Gcj0GgYxeoVR3n59hxaidA8Bm41uvzZcpx8ov0al2LHQLddM/Lm7om7wFXO0D/kyGZkisFaQuFAvB+Rs+VA3rvgK5VLz//P04fgewWkLoF9g+AoSJ5r7W4d8jPbx4LSP/b4yf4C4vSdIzDS13OAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAB3RJTUUH5gINEQwu6eRSBgAAABx0RVh0Q29tbWVudABDcmVhdGVkIHdpdGggR2xpbXBzZe5OGAcAAAAUSURBVBjTY/x/jgEPYGJgGJXGBAA5EwHhXz/1YwAAAABJRU5ErkJggg==
    DehydratedAvatarList:
      description: |
        An array of `DehydratedUserAvatar` objects
      type: array
      items:
        $ref: '#/components/schemas/DehydratedUserAvatar'
paths:
  /avatar/file:
    post:
      tags:
        - Avatars
      summary: 'Create a new avatar from a file attached as the body of a request'
      description: |
        Create a new avatar and store it in the system from the data in the body of the request.
      requestBody:
        content:
          'image/jpeg':
            schema:
              type: string
              format: binary
          'image/png':
            schema:
              type: string
              format: binary
      responses:
        '200':
          $ref: '#/components/responses/Avatar'
        '400':
          $ref: '#/components/responses/BadRequest'
        '413':
          $ref: '#/components/responses/PayloadTooLarge'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
  /avatar/uri:
    post:
      tags:
        - Avatars
      summary: 'Create a new avatar from a file encoded as a data URI'
      description: |
        Create a new avatar and store it in the system from the data in the body of the request.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AvatarUri'
      responses:
        '200':
          $ref: '#/components/responses/Avatar'
        '400':
          $ref: '#/components/responses/BadRequest'
        '413':
          $ref: '#/components/responses/PayloadTooLarge'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
  /avatar/uri/{id}:
    put:
      summary: Partially update a user's avatar by identifier with a data uri in the body
      tags:
        - Avatars
      parameters:
        - name: id
          in: path
          description: |
            Database `id` of the `Avatar` to update
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AvatarUri'
      responses:
        '200':
          $ref: '#/components/responses/Avatar'
        '400':
          $ref: '#/components/responses/BadRequest'
        '413':
          $ref: '#/components/responses/PayloadTooLarge'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
  /avatar/file/{id}:
    put:
      summary: Partially update a user's avatar by identifier with a file as a body
      tags:
        - Avatars
      parameters:
        - name: id
          in: path
          description: |
            Database `id` of the `Avatar` to update
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          'image/jpeg':
            schema:
              type: string
              format: binary
          'image/png':
            schema:
              type: string
              format: binary
      responses:
        '200':
          $ref: '#/components/responses/Avatar'
        '400':
          $ref: '#/components/responses/BadRequest'
        '413':
          $ref: '#/components/responses/PayloadTooLarge'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
    delete:
      summary: Delete a user's avatar by identifier
      tags:
        - Avatars
      parameters:
        - name: id
          in: path
          description: |
            Database `id` of the `Avatar` to remove
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '404':
          $ref: '#/components/responses/NotFoundError'
    get:
      summary: Retrieve a user's avatar by identifier
      tags:
        - Avatars
      parameters:
        - name: id
          in: path
          description: |
            Database `id` of the `Avatar` to retrieve
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          $ref: '#/components/responses/Avatar'
        '404':
          $ref: '#/components/responses/NotFoundError'
  /avatars:
    get:
      tags:
        - Avatars
      summary: 'List all avatars in the system'
      description: |
        Retrieves a listing of all user avatar objects in the system, without the actual image data associated.
      responses:
        '200':
          $ref: '#/components/responses/DehydratedUserAvatarList'

